Create database ArandaTest
GO
USE ArandaTest
GO

CREATE TABLE Category
(
	Id INT PRIMARY KEY IDENTITY(1,10) NOT NULL,
	Name NVARCHAR(200) NOT NULL,
	Active BIT NOT NULL,
	Create_Date DATETIME NOT NULL
)

CREATE TABLE Product
(
	Id BIGINT PRIMARY KEY IDENTITY(100, 1) NOT NULL,
	Id_Category INT NOT NULL,
	Name NVARCHAR(100) NOT NULL,
	ShortDescription NVARCHAR(300) NOT NULL,
	ImageP IMAGE NOT NULL,
	Active BIT NOT NULL,
	Create_Date DATETIME NOT NULL
)

ALTER TABLE Product  WITH CHECK ADD  CONSTRAINT FK_Category FOREIGN KEY(Id_Category)
REFERENCES Category (Id)
GO